import { describe, it, expect, afterEach, vi } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { renderCodexPrompt, installCodexPrompts } from '../../core/codexPrompts';
import { TASKWRIGHT_SKILL_NAMES } from '../../core/skillInstaller';
import type { SkillInstallResult } from '../../core/skillInstaller';

const SKILL_MD = `---
name: create-task
description: Turn a brief into draft tasks the human promotes on the board.
allowed-tools: mcp__taskwright__get_board, Skill(superpowers:brainstorming)
---

# Create task

Body of the skill. Read the tree first.
`;

describe('renderCodexPrompt', () => {
  it('strips the Claude YAML frontmatter and keeps the body', () => {
    const out = renderCodexPrompt(SKILL_MD, 'create-task');
    expect(out).not.toContain('allowed-tools');
    expect(out).not.toMatch(/^---/);
    expect(out).toContain('# Create task');
    expect(out).toContain('Body of the skill. Read the tree first.');
  });

  it('surfaces the skill description as a leading blockquote', () => {
    const out = renderCodexPrompt(SKILL_MD, 'create-task');
    expect(out).toContain('> Turn a brief into draft tasks the human promotes on the board.');
    // The description appears before the body.
    expect(out.indexOf('> Turn a brief')).toBeLessThan(out.indexOf('# Create task'));
  });

  it('appends an ARGUMENTS hook using Codex $ARGUMENTS substitution', () => {
    const out = renderCodexPrompt(SKILL_MD, 'create-task');
    expect(out.trimEnd().endsWith('ARGUMENTS: $ARGUMENTS')).toBe(true);
  });

  it('notes the file is generated by Taskwright from the skill source', () => {
    const out = renderCodexPrompt(SKILL_MD, 'create-task');
    expect(out).toContain('Generated by Taskwright');
    expect(out).toContain('create-task');
  });

  it('passes a body with no frontmatter through unchanged (plus header/footer)', () => {
    const out = renderCodexPrompt('# Plain skill\n\nJust a body.\n', 'execute-task');
    expect(out).toContain('# Plain skill');
    expect(out).toContain('Just a body.');
    expect(out.trimEnd().endsWith('ARGUMENTS: $ARGUMENTS')).toBe(true);
  });
});

describe('installCodexPrompts', () => {
  const dirs: string[] = [];

  afterEach(() => {
    for (const dir of dirs.splice(0)) {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  function tmpDir(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'taskwright-codex-'));
    dirs.push(dir);
    return dir;
  }

  function makeSkillDir(parent: string, name: string, content?: string): string {
    const dir = path.join(parent, name);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, 'SKILL.md'), content ?? `# ${name} skill content`, 'utf-8');
    return dir;
  }

  function makeAllSkills(parent: string): void {
    for (const name of TASKWRIGHT_SKILL_NAMES) {
      makeSkillDir(
        parent,
        name,
        `---\nname: ${name}\ndescription: d for ${name}\n---\n\n# ${name}\n`
      );
    }
  }

  it('writes one <name>.md prompt per Taskwright skill', () => {
    const extSkills = tmpDir();
    makeAllSkills(extSkills);
    const promptsDir = path.join(tmpDir(), 'prompts');

    const results = installCodexPrompts(extSkills, promptsDir, false);

    expect(results).toHaveLength(4);
    expect(results.every((r: SkillInstallResult) => r.action === 'created')).toBe(true);
    for (const name of TASKWRIGHT_SKILL_NAMES) {
      const file = path.join(promptsDir, `${name}.md`);
      expect(fs.existsSync(file)).toBe(true);
      const content = fs.readFileSync(file, 'utf-8');
      expect(content).toContain(`# ${name}`);
      expect(content).toContain('ARGUMENTS: $ARGUMENTS');
    }
  });

  it('skips existing prompts when overwrite is false and preserves their content', () => {
    const extSkills = tmpDir();
    makeAllSkills(extSkills);
    const promptsDir = tmpDir();
    fs.writeFileSync(path.join(promptsDir, 'create-task.md'), 'existing prompt', 'utf-8');

    const results = installCodexPrompts(extSkills, promptsDir, false);

    const byName: Record<string, SkillInstallResult> = {};
    for (const r of results) byName[r.name] = r;
    expect(byName['create-task'].action).toBe('skipped');
    expect(byName['execute-task'].action).toBe('created');
    expect(fs.readFileSync(path.join(promptsDir, 'create-task.md'), 'utf-8')).toBe(
      'existing prompt'
    );
  });

  it('overwrites existing prompts when overwrite is true', () => {
    const extSkills = tmpDir();
    makeAllSkills(extSkills);
    const promptsDir = tmpDir();
    fs.writeFileSync(path.join(promptsDir, 'create-task.md'), 'old prompt', 'utf-8');

    const results = installCodexPrompts(extSkills, promptsDir, true);

    const byName: Record<string, SkillInstallResult> = {};
    for (const r of results) byName[r.name] = r;
    expect(byName['create-task'].action).toBe('overwritten');
    expect(fs.readFileSync(path.join(promptsDir, 'create-task.md'), 'utf-8')).not.toBe(
      'old prompt'
    );
  });

  it('surfaces missing skill sources via the handler and still installs the rest', () => {
    const extSkills = tmpDir();
    makeSkillDir(extSkills, 'create-task');
    makeSkillDir(extSkills, 'execute-task');
    const promptsDir = tmpDir();
    const onMissing = vi.fn();

    const results = installCodexPrompts(extSkills, promptsDir, false, onMissing);

    expect(results.map((r: SkillInstallResult) => r.name)).toEqual(['create-task', 'execute-task']);
    expect(onMissing).toHaveBeenCalledTimes(2);
    expect(onMissing).toHaveBeenCalledWith(
      'index-codebase',
      path.join(extSkills, 'index-codebase', 'SKILL.md')
    );
    expect(fs.existsSync(path.join(promptsDir, 'index-codebase.md'))).toBe(false);
  });

  it('is idempotent: a second run with overwrite=false skips everything', () => {
    const extSkills = tmpDir();
    makeAllSkills(extSkills);
    const promptsDir = tmpDir();

    installCodexPrompts(extSkills, promptsDir, false);
    const second = installCodexPrompts(extSkills, promptsDir, false);

    expect(second).toHaveLength(4);
    expect(second.every((r: SkillInstallResult) => r.action === 'skipped')).toBe(true);
  });

  it('renders the real committed skills without throwing', () => {
    // src/test/unit -> repo root is three levels up.
    const repoRoot = path.resolve(__dirname, '..', '..', '..');
    const realSkillsDir = path.join(repoRoot, '.claude', 'skills');
    const promptsDir = tmpDir();

    const results = installCodexPrompts(realSkillsDir, promptsDir, true);

    expect(results.map((r: SkillInstallResult) => r.name).sort()).toEqual(
      [...TASKWRIGHT_SKILL_NAMES].sort()
    );
    for (const name of TASKWRIGHT_SKILL_NAMES) {
      const content = fs.readFileSync(path.join(promptsDir, `${name}.md`), 'utf-8');
      // Frontmatter stripped, description carried over, arguments hook added.
      expect(content.startsWith('---')).toBe(false);
      expect(content).toContain('ARGUMENTS: $ARGUMENTS');
    }
  });
});
