import * as fs from 'fs';
import * as path from 'path';
import { TASKWRIGHT_SKILL_NAMES } from './skillInstaller';
import type { SkillInstallResult, MissingSkillSourceHandler } from './skillInstaller';

/**
 * Per-agent renderer for Codex: translate the four user-facing Taskwright
 * skills (`.claude/skills/<name>/SKILL.md`) into Codex custom prompts
 * (`$CODEX_HOME/prompts/<name>.md`, invoked as `/<name>`), generated from the
 * SAME source content — one source of truth, per-agent renderers. The Claude
 * Code installer (`skillInstaller.ts`) copies the skill directories verbatim;
 * this renderer strips the Claude-specific YAML frontmatter (`allowed-tools`
 * has no Codex equivalent), surfaces the skill description, and appends a
 * Codex `$ARGUMENTS` substitution hook mirroring how the Claude Skill tool
 * passes arguments.
 */

/** Match a leading YAML frontmatter block (--- ... ---) at the top of SKILL.md. */
const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;

/**
 * Render one skill's SKILL.md as a Codex custom prompt. The body is carried
 * verbatim; only the frontmatter is translated (description → leading
 * blockquote). Ends with an `ARGUMENTS: $ARGUMENTS` line so `/name args`
 * reaches the prompt body the same way the Claude Skill tool appends
 * `ARGUMENTS: <args>`.
 */
export function renderCodexPrompt(skillMd: string, name: string): string {
  let body = skillMd;
  let description: string | undefined;

  const fmMatch = FRONTMATTER_RE.exec(skillMd);
  if (fmMatch) {
    body = skillMd.slice(fmMatch[0].length);
    const descMatch = /^description:\s*(.+)$/m.exec(fmMatch[1]);
    if (descMatch) {
      description = descMatch[1].trim();
    }
  }

  const parts: string[] = [
    `<!-- Generated by Taskwright from the ${name} skill (.claude/skills/${name}/SKILL.md). Do not edit by hand — re-run the Taskwright agent setup to refresh. -->`,
    '',
  ];
  if (description) {
    parts.push(`> ${description}`, '');
  }
  parts.push(body.trim(), '', 'ARGUMENTS: $ARGUMENTS', '');
  return parts.join('\n');
}

function defaultMissingSource(name: string, srcFile: string): void {
  console.warn(
    `[taskwright] Skill source missing, skipping Codex prompt "${name}" (expected at ${srcFile}). ` +
      `A packaged install ships these under dist/skills/ — rebuild (bun run build) or reinstall the extension.`
  );
}

/**
 * Install all Taskwright skills as Codex custom prompts (`<promptsDir>/<name>.md`).
 *
 * Mirrors `installTaskwrightSkills`: idempotent by default (an existing prompt
 * file is skipped unless `overwrite` is set), and a missing skill source is
 * surfaced through the handler rather than failing the whole setup.
 *
 * @param extSkillsDir - The extension's bundled skills directory (dist/skills).
 * @param promptsDir - Codex prompts directory (usually `$CODEX_HOME/prompts`).
 * @param overwrite - Whether to replace existing prompt files.
 * @param onMissingSource - Invoked when a skill's SKILL.md is absent.
 */
export function installCodexPrompts(
  extSkillsDir: string,
  promptsDir: string,
  overwrite: boolean,
  onMissingSource: MissingSkillSourceHandler = defaultMissingSource
): SkillInstallResult[] {
  const results: SkillInstallResult[] = [];
  fs.mkdirSync(promptsDir, { recursive: true });

  for (const name of TASKWRIGHT_SKILL_NAMES) {
    const srcFile = path.join(extSkillsDir, name, 'SKILL.md');
    if (!fs.existsSync(srcFile)) {
      onMissingSource(name, srcFile);
      continue;
    }

    const destFile = path.join(promptsDir, `${name}.md`);
    const existed = fs.existsSync(destFile);
    if (existed && !overwrite) {
      results.push({ name, action: 'skipped' });
      continue;
    }

    const rendered = renderCodexPrompt(fs.readFileSync(srcFile, 'utf-8'), name);
    fs.writeFileSync(destFile, rendered, 'utf-8');
    results.push({ name, action: existed ? 'overwritten' : 'created' });
  }

  return results;
}
